root: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
plugins:
  - "@typescript-eslint/eslint-plugin"
  - "eslint-plugin-tsdoc"
rules:
  "@typescript-eslint/no-empty-function": off
parser: "@typescript-eslint/parser"
parserOptions:
  project: true
  # tsconfigRootDir: __dirname
  ecmaVersion: 2018
  sourceType: module
